<?php
/** Pricing plans Flexible Content layout. */
?>
<section class="<?php echo esc_attr( ptvx_ui_class( 'section' ) ); ?> ptvx-plans-section bg-linear-to-b from-white to-[#f9fbfe]" id="pricing">
	<div class="<?php echo esc_attr( ptvx_ui_class( 'container' ) ); ?>">
		<header class="<?php echo esc_attr( ptvx_ui_class( 'section_header' ) ); ?>"><?php if ( get_sub_field( 'heading' ) ) : ?><h2><?php the_sub_field( 'heading' ); ?></h2><?php endif; ?><?php if ( get_sub_field( 'intro' ) ) : ?><p class="m-0 text-base text-ptvx-muted"><?php the_sub_field( 'intro' ); ?></p><?php endif; ?></header>
		<?php if ( have_rows( 'items' ) ) : ?><div class="ptvx-plan-grid mx-auto grid max-w-[66.25rem] grid-cols-1 items-stretch gap-6 sm:grid-cols-2 lg:grid-cols-3"><?php while ( have_rows( 'items' ) ) : the_row(); $is_highlighted = get_sub_field( 'highlighted' ); $plan_class = ptvx_ui_class( 'card' ) . ' ptvx-plan relative flex flex-col overflow-hidden rounded-[0.875rem] p-7.5'; if ( $is_highlighted ) { $plan_class .= ' ptvx-plan--highlighted border-2 border-ptvx-red shadow-[0_24px_56px_rgb(238_38_52/16%)] lg:-translate-y-3'; } ?><article class="<?php echo esc_attr( $plan_class ); ?>"><?php if ( $is_highlighted ) : ?><p class="ptvx-plan__badge absolute top-0 right-0 left-0 m-0 bg-ptvx-red p-2 text-center text-xs font-extrabold tracking-[0.06em] text-white uppercase"><?php echo esc_html( ptvx_label( 'most_popular' ) ); ?></p><?php endif; ?><p class="ptvx-plan__name <?php echo $is_highlighted ? 'mt-5.75 ' : ''; ?>m-0 text-xl font-extrabold text-ptvx-red uppercase"><?php the_sub_field( 'name' ); ?></p><?php if ( get_sub_field( 'duration' ) ) : ?><p class="ptvx-plan__duration my-1.25 text-sm font-semibold text-ptvx-muted"><?php the_sub_field( 'duration' ); ?></p><?php endif; ?><p class="ptvx-plan__price my-4 text-[2.35rem] font-extrabold tracking-[-0.04em] text-ptvx-navy"><?php the_sub_field( 'price' ); ?></p><?php $features = ptvx_lines( get_sub_field( 'features' ) ); if ( $features ) : ?><ul class="grid flex-1 list-none gap-2.25 p-0 pb-6.75 text-sm text-[#46556b]"><?php foreach ( $features as $feature ) : ?><li class="relative pl-5.25"><?php echo esc_html( $feature ); ?></li><?php endforeach; ?></ul><?php endif; ?><?php echo ptvx_link_html( ptvx_offer_link( get_sub_field( 'offer' ), array( 'title' => get_sub_field( 'cta_label' ) ?: ptvx_label( 'view_plans' ) ) ), 'ptvx-button ptvx-plan__button w-full' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></article><?php endwhile; ?></div><?php endif; ?>
	</div>
</section>
